### PR TITLE
MailgunMail: Usage of meteor http module has changed #468

### LINKED ISSUE #468: Unable to send mails via mailgun - TypeError: Cannot read property 'post' of  undefined
Hi,
i am using mailgun for email. I have configured the domain and `4minitz_settings.json
A snippet of my 4minitz_settings.json is 

"//3": "below option configures if and how to send E-Mails",
    "email": {
        "//3.1": "Switch on/off E-Mail sending",
        "enableMailDelivery": true,
        "//3.2": "Choose one of the below mail deliver methods",
        "mailDeliverer": "mailgun",

"fallbackEMailSenderAddress": "noreply@yourdomain.com",
        "smtp": {
            "mailUrl": "smtp://postmaster@sandbox8560f461222d4517a668a043c72d5f6f.mailgun.org:21b6c12e$
        },
        "mailgun": {
            "apiKey": "4040800f243dc2d9ed87485f1b5a5efb-c8e745ec-90b5f2a3",
            "domain": "sandbox8560f461222d4517a668a043c72d5f6f.mailgun.org",
            "apiUrl": "https://api.mailgun.net/v3/sandbox8560f461222d4517a668a043c72d5f6f.mailgun.org"
        },

        "//3.6": "Send an e-mail with a verification token to new user when enableMailDelivery:true",
        "sendVerificationEmail": true,

        "//3.7": "Enable form to resend the verification token to users e-mail when enableMailDelivery$        "showResendVerificationEmailLink": true,

        "//3.8": "Enable form to perform user password reset when enableMailDelivery:true",
        "showForgotPasswordLink": true

When i try to send Agenda I have this message to video "OK Agenda was send to recipient successfully"
but the log shows the following error
Error: TypeError: Cannot read property 'post' of  undefined

### PR DESCRIPTION
**Pull request by felixble**
Closes #468

### CODE REVIEW

**Comment by felixble** [comment]
With this fix I could sent mails via mailgun from my local 4minitz environment. It is important to set the `apiUrl` in the 4minitz settings to `https://api.mailgun.net/v3` and do not append the custom domain.

File: imports/mail/MailgunMail.js [hunk 1]
```diff
@@ -34,7 +34,17 @@ export class MailgunMail extends Mail {
         }
 
         // Send the request
-        Meteor.http.post(postURL, options); // do not pass callback so the post request will run synchronously
+        const result = HTTP.post(postURL, options); // do not pass callback so the post request will run synchronously
+        this._verifyStatus(result);
+    }
+
+    _verifyStatus(result) {
+        if (result.data && result.data.message === 'Queued. Thank you.') {
```
Comment (migerh) [inline imports/mail/MailgunMail.js:42]: Is this returned by the mailgun service? If so we should not test that as it may change at any time.

Test HTTP status codes and the existence of data, but not specific strings unless it is guaranteed that they don't change.

**Review by migerh — CHANGES_REQUESTED** [review]

File: imports/mail/MailgunMail.js (hunk 1 above)
Comment (felixble) [reply imports/mail/MailgunMail.js:42]: I totally see your point. Unfortunately, we cannot check any status code since we get an http 200 in either case: success and error 🤷‍♂️. We could check if the attribute `id` is given.

Since we sent the emails asynchronously and currently do not notify the user if the mail could not be sent I want to notify the sysadmin in any case something is different than expected.

Comment (migerh) [reply imports/mail/MailgunMail.js:42]: I see. Just checked the Mailgun API and there really seems to be no reliable way to check for success.

**Review by migerh — APPROVED** [review]
